site: Gutterfly.net
title: Gutterfly
greetings: Welcome.
description: >-
  A development blog for Gutterfly
lang: en-US
timezone:  America/New_York
#repo: https://github.com/p0wex/Gesko # site repo [optional]
data-theme: dark # default theme "dark" | "light"
discus-identifier: NathanStanley # replace with your disqus shortname

author:
  name: Nathan Stanley
  bio: Gutterfly Developer
  userpicture: 
  username: # general username
  github: # github username
  twitter: # twitter username
  email: nathan@gutterfly.net # email adress

# Font Settings
googlewebfonts: family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900

# URL settings
url: "https://gutterfly.net" # Domain Name of host. [username].github.io for github pages
baseurl: "" # sub folder for jekyll site. only if jekyll site not in root of host. leave blank if not wishd. always add / in front.
permalink: pretty

# local
# url: "http://localhost:4000" # 
# baseurl: "" # 


markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge


exclude:
  - .jekyll-cache
  - .obsidian
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - CONTRIBUTING.md
  
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-relative-links

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:month/:day/:slug
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

relative_links:
  enabled:     true
  collections: false


